version: '3.8'

services:
  postgres-barberia:
    image: postgres:15
    container_name: postgres-barberia
    restart: always
    environment:
      POSTGRES_DB: barberia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=es_ES.UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
      - ./config:/etc/postgresql
    networks:
      - barberia-network-pg
    shm_size: 256mb
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_destination=stderr"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  barberia-network-pg:
    driver: bridge

volumes:
  postgres-data: